
// Action types for members
export const REQUEST_START = 'REQUEST_START';
export const GET_MEMBER_SUCCESS = 'GET_MEMBER_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const POST_MEMBER_SUCCESS = 'POST_MEMBER_SUCCESS';
export const DELETE_MEMBER_SUCCESS = 'DELETE_MEMBER_SUCCESS';
