
// Action types for members
export const GET_REQUEST_START = 'GET_REQUEST_START';
export const GET_MEMBER_SUCCESS = 'GET_MEMBER_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

export const POST_REQUEST_START = 'POST_REQUEST_START';
export const POST_MEMBER_SUCCESS = 'POST_MEMBER_SUCCESS';

export const DELETE_REQUEST_START = 'DELETE_REQUEST_START';
export const DELETE_MEMBER_SUCCESS = 'DELETE_MEMBER_SUCCESS';

export const DELETE_ALL_REQUEST_START = 'DELETE_ALL_REQUEST_START';
export const DELETE_ALL_MEMBERS_SUCCESS = "DELETE_ALL_MEMBERS_SUCCESS";
