
// Action types for packages
export const GET_REQUEST_START = 'GET_REQUEST_START';
export const GET_PACKAGE_SUCCESS = 'GET_PACKAGE_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const POST_PACKAGE_SUCCESS = 'POST_PACKAGE_SUCCESS';
export const DELETE_PACKAGE_SUCCESS = 'DELETE_PACKAGE_SUCCESS';
export const UPDATE_PACKAGE_SUCCESS = 'UPDATE_PACKAGE_SUCCESS';
export const DELETE_REQUEST_START = 'DELETE_REQUEST_START';
export const UPDATE_REQUEST_START = 'UPDATE_REQUEST_START';
export const POST_REQUEST_START = 'POST_REQUEST_START';
