// Action types for private msgs
export const GET_REQUEST_START = 'GET_REQUEST_START';
export const GET_MSG_SUCCESS = 'GET_MSG_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const POST_MSG_SUCCESS = 'POST_MSG_SUCCESS';
export const DELETE_MSG_SUCCESS = 'DELETE_MSG_SUCCESS';
export const UPDATE_MSG_SUCCESS = 'UPDATE_MSG_SUCCESS';
export const DELETE_REQUEST_START = 'DELETE_REQUEST_START';
export const UPDATE_REQUEST_START = 'UPDATE_REQUEST_START';
export const POST_REQUEST_START = 'POST_REQUEST_START';