
// Action types for trainers
export const GET_REQUEST_START = 'GET_REQUEST_START';
export const GET_TRAINERS_SUCCESS = 'GET_TRAINERS_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const POST_TRAINERS_SUCCESS = 'POST_TRAINERS_SUCCESS';
export const DELETE_TRAINERS_SUCCESS = 'DELETE_TRAINERS_SUCCESS';
export const UPDATE_TRAINERS_SUCCESS = 'UPDATE_TRAINERS_SUCCESS';
export const DELETE_REQUEST_START = 'DELETE_REQUEST_START';
export const UPDATE_REQUEST_START = 'UPDATE_REQUEST_START';
export const POST_REQUEST_START = 'POST_REQUEST_START';
