// Action types for block users
export const REQUEST_START = 'REQUEST_START';
export const GET_BLOCKED_USERS_SUCCESS = 'GET_BLOCKED_USERS_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS';
export const UNBLOCK_USER_SUCCESS = 'UNBLOCK_USER_SUCCESS';