
// Action types for Users
export const REQUEST_START = 'REQUEST_START';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const POST_USER_SUCCESS = 'POST_USER_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const DELETE_ALL_USERS_SUCCESS = "DELETE_ALL_USERS_SUCCESS"
