
// Action types for message
export const REQUEST_START = 'REQUEST_START';
export const GET_MESSAGE_SUCCESS = 'GET_MEMBER_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const POST_MESSAGE_SUCCESS = 'POST_MEMBER_SUCCESS';
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MEMBER_SUCCESS';
