
// Action types for message
export const GET_REQUEST_START = 'GET_REQUEST_START';
export const GET_MESSAGE_SUCCESS = 'GET_MESSAGE_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const POST_MESSAGE_SUCCESS = 'POST_MESSAGE_SUCCESS';
export const DELETE_MESSAGE_SUCCESS = 'DELETE_MESSAGE_SUCCESS';
export const UPDATE_MESSAGE_SUCCESS = 'UPDATE_MESSAGE_SUCCESS';
export const DELETE_REQUEST_START = 'DELETE_REQUEST_START';
export const UPDATE_REQUEST_START = 'UPDATE_REQUEST_START';
