
// Action types for supplement store
export const GET_REQUEST_START = 'GET_REQUEST_START';
export const GET_SUPPLEMENTS_SUCCESS = 'GET_SUPPLEMENTS_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const POST_SUPPLEMENTS_SUCCESS = 'POST_SUPPLEMENTS_SUCCESS';
export const DELETE_SUPPLEMENTS_SUCCESS = 'DELETE_SUPPLEMENTS_SUCCESS';
export const UPDATE_SUPPLEMENTS_SUCCESS = 'UPDATE_SUPPLEMENTS_SUCCESS';
export const DELETE_REQUEST_START = 'DELETE_REQUEST_START';
export const UPDATE_REQUEST_START = 'UPDATE_REQUEST_START';
export const POST_REQUEST_START = 'POST_REQUEST_START';
