// Action types for block members
export const REQUEST_START = 'REQUEST_START';
export const GET_BLOCKED_MEMBERS_SUCCESS = 'GET_BLOCKED_MEMBERS_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const BLOCK_MEMBER_SUCCESS = 'BLOCK_MEMBER_SUCCESS';
export const UNBLOCK_MEMBER_SUCCESS = 'UNBLOCK_MEMBER_SUCCESS';