// Action types for block members
export const REQUEST_START = 'REQUEST_START';
export const GET_BLOCKED_USER_SUCCESS = 'GET_BLOCKED_USER_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';
export const BLOCK_MEMBER_SUCCESS = 'BLOCK_MEMBER_SUCCESS';
export const UNBLOCK_USER_SUCCESS = 'UNBLOCK_USER_SUCCESS';